Feature/pm 527 cpp client side odrive
project-march/controller-research pull request #4
Opened 2020-07-07 15:39 UTC by JorisWeeda

Closes PM-527

## Description
With this PR it should be possible to control the Odrive using CPP-code and later on ROS control. It is based on the native communication protocol which is also used by the official _odrivetool shell_. This is accomplished by writing a usb driver to send and receive data over the TX/RX communication line of the odrive.

Within this PR a basic program is included to publish data from the Odrive to a ROS topic to generaly display the usage and functionalities of the program. The Json file consists of the default configurations which are set during the startup sequence. 

## Changes
* Include cpp USB driver for the odrive.
* basic program to publish odrive data
* configuration file for the March odrive

2020-07-29 18:19 UTC, Roelemans requested changes
Looks good! (though I don't 100% understand everything :sweat_smile:).

2020-07-29 18:19 UTC, Roelemans commented on odrive_interface/config/odrive_settings/march_odrive.json
> +        "value":0
Hmm 0 meant no watchdog right?

2020-07-29 18:19 UTC, Roelemans commented on odrive_interface/config/odrive_settings/march_odrive.json
> +[
How do you create this json file? do you have to manually edit it?

2020-07-29 18:19 UTC, Roelemans commented on odrive_interface/include/odrive_interface/odrive.hpp
> +  int setConfigurations(const std::string& configuration_json_path);
I think you oopsied your docstring here ;)

2020-08-06 09:05 UTC, JorisWeeda commented on odrive_interface/config/odrive_settings/march_odrive.json
> +        "value":0
yes indeed. When using the odrive u have to manually update the watchdog timer in the hardware interface loop running on the master, eg;
```
  while (ros::ok())
  {
    // update watchdog
    odrives_objects[0].function("axis0.watchdog_feed");
    odrives_objects[1].function("axis1.watchdog_feed");

    r.sleep();
    ros::spinOnce();
  }
```
But i got some problems with the update function so decided to leave it out temporarily.

2020-08-06 09:05 UTC, JorisWeeda commented on odrive_interface/config/odrive_settings/march_odrive.json
> +[
I indeed manually created this, seemed like the fasted solution.

2020-08-06 09:06 UTC, JorisWeeda commented on odrive_interface/include/odrive_interface/odrive.hpp
> +  int setConfigurations(const std::string& configuration_json_path);
i did ):

2020-08-06 13:51 UTC, Roelemans commented on odrive_interface/include/odrive_interface/odrive.hpp
> +  int setConfigurations(const std::string& configuration_json_path);
How can you be like this

2020-08-08 07:28 UTC, Roelemans requested changes

2020-08-08 07:28 UTC, Roelemans commented on odrive_interface/include/odrive_interface/odrive.hpp
> +  int setConfigurations(const std::string& configuration_json_path);
? :'(

2020-08-11 07:39 UTC, JorisWeeda commented on odrive_interface/include/odrive_interface/odrive.hpp
> +  int setConfigurations(const std::string& configuration_json_path);
me so sorry

2020-08-12 12:00 UTC, Roelemans approved these changes

2020-08-12 12:00 UTC, merged